"""Move a whole TACU working copy to another machine, as one file.

`ti backup` saves what TACU *knows* — history, clipboard, settings. This saves
what TACU *is*: the source tree, including everything git deliberately ignores.
The local holding pen, the release-validation harness and the untracked notes
are the parts a clone cannot give you, and they are the reason copying the repo
from GitHub is not the same as moving your working copy.

What is left out is only what the other machine will rebuild for itself:
installed packages, virtual environments, caches and build output. Those are
large, machine-specific, and wrong to carry across anyway.
"""

from __future__ import annotations

import fnmatch
import os
import re
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

# India has no daylight saving, so a fixed offset is exact and does not depend
# on the machine's own timezone being right.
IST = timezone(timedelta(hours=5, minutes=30), "IST")
ARCHIVE_PREFIX = "tacu"
DEFAULT_DESCRIPTION = "snapshot"

# Directories the other machine recreates by installing. Carrying them across
# is slow, large, and often broken — a macOS virtualenv is useless on Linux.
DEPENDENCY_DIRS = frozenset({
    "node_modules", ".venv", "venv", "env", ".env.d", "site-packages",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox",
    ".nox", ".gradle", ".m2", "target", ".cargo", "vendor", "bower_components",
    ".next", ".nuxt", ".parcel-cache", ".turbo", ".cache", "htmlcov",
    ".ipynb_checkpoints", ".terraform", "Pods", "DerivedData",
})
# Build output. Regenerated by a build, never edited by hand.
BUILD_DIRS = frozenset({"build", "dist", ".eggs"})
DEPENDENCY_GLOBS = ("*.egg-info", "*.dist-info")
DEPENDENCY_FILES = ("*.pyc", "*.pyo", "*.pyd", "*.class", "*.o", "*.so.tmp",
                    ".DS_Store", "Thumbs.db")

# Files worth naming out loud before they travel: a copy of the tree carries
# them in the clear, and the archive usually lands in a shared folder.
SENSITIVE_GLOBS = ("*.pem", "*.key", "*.p12", "*.pfx", "id_rsa", "id_ed25519",
                   ".env", ".env.*", "credentials.json", "secrets.json",
                   "*.keystore", "*.jks")
_SAFE_DESCRIPTION = re.compile(r"[^A-Za-z0-9]+")
_NAME_RE = re.compile(
    r"^tacu_(?P<time>\d{4})_IST_(?P<day>\d{2})_(?P<month>[A-Za-z]{3})_(?P<year>\d{4})"
    r"_(?P<description>.+)$")


@dataclass
class MigratePlan:
    """What the archive will contain, decided before anything is written."""

    root: Path
    archive: Path
    files: list[Path] = field(default_factory=list)
    total_bytes: int = 0
    skipped_dirs: list[str] = field(default_factory=list)
    skipped_bytes: int = 0
    excluded_dirs: list[str] = field(default_factory=list)
    excluded_bytes: int = 0
    sensitive: list[str] = field(default_factory=list)
    largest: list[tuple[str, int]] = field(default_factory=list)


def archive_stamp(when: datetime | None = None) -> str:
    """HHMM_IST_DD_MMM_YYYY for the moment the snapshot was taken."""

    moment = (when or datetime.now(timezone.utc)).astimezone(IST)
    return moment.strftime("%H%M_IST_%d_%b_%Y")


def describe_slug(description: str) -> str:
    """Turn a sentence into something that survives being a file name."""

    cleaned = _SAFE_DESCRIPTION.sub("-", (description or "").strip()).strip("-")
    return (cleaned[:60].strip("-") or DEFAULT_DESCRIPTION)


def archive_name(description: str = "", when: datetime | None = None) -> str:
    return f"{ARCHIVE_PREFIX}_{archive_stamp(when)}_{describe_slug(description)}"


def parse_archive_name(name: str) -> dict[str, str] | None:
    """Read back what an archive says about itself, for listings."""

    match = _NAME_RE.match(Path(name).stem)
    return dict(match.groupdict()) if match else None


def _matches_any(name: str, patterns: tuple[str, ...]) -> bool:
    return any(fnmatch.fnmatch(name, pattern) for pattern in patterns)


def is_dependency_dir(name: str) -> bool:
    return (name in DEPENDENCY_DIRS or name in BUILD_DIRS
            or _matches_any(name, DEPENDENCY_GLOBS))


def is_sensitive(relative: str) -> bool:
    name = Path(relative).name
    return _matches_any(name, SENSITIVE_GLOBS) and name != ".env.example"


def _directory_size(path: Path) -> int:
    total = 0
    for base, _dirs, names in os.walk(path, onerror=lambda _error: None):
        for name in names:
            try:
                total += (Path(base) / name).lstat().st_size
            except OSError:
                continue
    return total


def plan_migration(root: Path, archive: Path, *,
                   exclude: tuple[str, ...] = ()) -> MigratePlan:
    """Walk the tree once and decide what travels, without writing anything.

    Nothing is skipped for being untracked: the holding pen and the private
    test harness are exactly what a fresh clone would not give you. Only
    installed and generated artefacts are left behind.
    """

    root = root.resolve()
    plan = MigratePlan(root=root, archive=archive)
    per_directory: dict[str, int] = {}
    for base, directories, names in os.walk(root, onerror=lambda _error: None):
        base_path = Path(base)
        relative_base = base_path.relative_to(root).as_posix()
        keep: list[str] = []
        for name in sorted(directories):
            child = f"{relative_base}/{name}" if relative_base != "." else name
            if is_dependency_dir(name):
                plan.skipped_dirs.append(child)
                plan.skipped_bytes += _directory_size(base_path / name)
                continue
            if _matches_any(child, exclude):
                # Asked for by the caller, so reported separately: it is a
                # choice, not something the other machine will rebuild.
                plan.excluded_dirs.append(child)
                plan.excluded_bytes += _directory_size(base_path / name)
                continue
            keep.append(name)
        directories[:] = keep
        for name in sorted(names):
            path = base_path / name
            relative = path.relative_to(root).as_posix()
            if _matches_any(name, DEPENDENCY_FILES) or _matches_any(relative, exclude):
                continue
            if path.is_symlink() or not path.is_file():
                continue
            try:
                size = path.lstat().st_size
            except OSError:
                continue
            # Never put the archive inside itself.
            if path.resolve() == archive.resolve():
                continue
            plan.files.append(path)
            plan.total_bytes += size
            if is_sensitive(relative):
                plan.sensitive.append(relative)
            top = relative.split("/", 1)[0] if "/" in relative else relative
            per_directory[top] = per_directory.get(top, 0) + size
    plan.largest = sorted(per_directory.items(), key=lambda pair: -pair[1])[:8]
    return plan


def write_archive(plan: MigratePlan, *, on_progress=None) -> Path:
    """Write the zip, with every path under one folder named like the archive.

    Unzipping therefore produces one directory, not a heap of files in whatever
    folder the archive happened to be sitting in.
    """

    top = plan.archive.stem
    plan.archive.parent.mkdir(parents=True, exist_ok=True)
    temporary = plan.archive.with_name(plan.archive.name + ".partial")
    written = 0
    try:
        with zipfile.ZipFile(temporary, "w", zipfile.ZIP_DEFLATED,
                             compresslevel=6, allowZip64=True) as bundle:
            for path in plan.files:
                relative = path.relative_to(plan.root).as_posix()
                try:
                    bundle.write(path, f"{top}/{relative}")
                except (OSError, ValueError):
                    continue
                written += 1
                if on_progress is not None:
                    on_progress(written, len(plan.files), relative)
        temporary.replace(plan.archive)
    finally:
        temporary.unlink(missing_ok=True)
    if os.name != "nt":
        try:
            # The tree can carry .env files and keys; do not leave it world-readable.
            plan.archive.chmod(0o600)
        except OSError:
            pass
    return plan.archive


def default_destination(root: Path) -> Path:
    """One directory above the working copy, as asked — never inside it."""

    return root.resolve().parent


def human_bytes(count: int) -> str:
    size = float(count)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"
